name = "cloudcors"
main = "src/index.ts"
compatibility_date = "2022-06-14"

[build]
command = "node build.js"

[vars]
ENDPOINT_ALLOWLIST = ""
# ENDPOINT_ALLOWLIST = """
#     [
#         "www.google.com",
#     ]
# """
