name = "cloudflare-worker-token-service"
main = "src/index.ts"
compatibility_date = "2022-06-14"

[vars]
ENDPOINT_ALLOWLIST = """
    [
        "www.humblebundle.com",
        "standardebooks.org",
        "catalog.feedbooks.com",
        "m.gutenberg.org",
        "www.gutenberg.org"
    ]
"""
