name = "cloudcors"
main = "src/index.ts"
compatibility_date = "2022-06-14"

[build]
command = "node build.js"

[vars]
ENDPOINT_ALLOWLIST = """
    [
        "www.humblebundle.com",
        "standardebooks.org",
        "catalog.feedbooks.com",
        "m.gutenberg.org",
        "www.gutenberg.org",
        "www.soundcloud.com",
        "api-v2.soundcloud.com"
    ]
"""
