name = "cloudcors"
type = "webpack"
workers_dev = true
webpack_config = "webpack.config.js"

[vars]
ENDPOINT_ALLOWLIST = """
    [
        "www.humblebundle.com",
        "standardebooks.org",
        "catalog.feedbooks.com",
        "m.gutenberg.org",
        "www.gutenberg.org"
    ]
"""
